name: Auto Build TypeScript

on:
  push:
    branches:
      - main  # หรือ master ขึ้นอยู่กับ branch หลักของคุณ

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: auto build dist"
          file_pattern: 'dist/*'
